### PR TITLE
Minimal, Faster, reduced bloat and Tmux-powered

### PR DESCRIPTION
**Pull request by jancarloviray**
Just letting you know that I did some work taking out the bloat but adding some awesome stuff. 

I disabled a lot of php/ruby/rust, etc plugins btw. Lots of config so yes, it will conflict with yours :)

Just fyi.

### CODE REVIEW

**Comment by willopez** [comment]
Looks good and thanks. This is good progress towards having a vim distribution to meet our needs specifically. 

It would be good to have some node plugins to aid node dev, are you aware of this page? https://github.com/joyent/node/wiki/Vim-Plugins

**Comment by jancarloviray** [comment]
Awesome. Yeah, 90% of the good ones are there. I did not add unstable/beta ones.

**Comment by willopez** [comment]
Hey collaborating on github like is, IS cool. It's on demand collaborating :)

**Comment by willopez** [comment]
https://github.com/spf13/hugo

**Comment by jancarloviray** [comment]
already made one: https://github.com/jancarloviray/jancarloviray.github.io :) or... 
linked to [www.jancarloviray.com](http://www.jancarloviray.com) (freely hosted through github! :)

**Pull request closed without merging**
